nodes:
- input.visual:
    source: ./data/testing.mp4
    saved_video_fps: 1
- model.jde
- dabble.statistics:
    maximum: obj_attrs["ids"]
- custom_nodes.draw.motion_detector
- draw.tag:
    show: ["ids"]
- output.screen
